### PR TITLE
build: use standard Makefile rules and variables

### PR DESCRIPTION
**Pull request by cbs228**
Use standard gcc/make variables:

* `CPPFLAGS`: for preprocessor flags
* `CFLAGS`: for build flags
* `LDLIBS`: for dynamically linking libraries
* `LDFLAGS`:  for specifying linker-only options

The existing Makefile uses the [implicit rule](https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html#index-C_002c-rule-to-compile) for building object files. Switch to using the implicit rule for [linking](https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html#index-linking_002c-predefined-rule-for) the final executable as well.

* Since the source and object files have a different name than the final executable, we must state the rule **explicitly**.

* If the main source file were named `ardopcf.c`, we could use the implicit linking rule instead. Let me know if you would rather I rename the file and use the implicit rule. Renames can negatively impact ongoing merges and rebases.

The use of more standardized rules permits overriding these variables at build-time. This can be used—among other things—to enable ASAN. See #37.

Also ensure that `make clean` always succeeds. Protect `rm` from unwanted filename-as-argument interpretation.

### CODE REVIEW

**Comment by pflarue** [comment]
I have limited experience with anything more than the most basic uses of `make`, so I welcome these changes.  I'll test them, and unless they cause problems, merge them shortly.  Would you like to also provide changes to Makefile_mingw32?

In reference to your comment about explicitly naming the executable, I prefer not to rename files that exist in g8bpq/ardop unless there is a good reason to do so.  I believe that unnecessary renaming of such core files might make it more difficult for anyone wanting to merge bug fixes or newer features from this repository into g8bpq/ardop or other forks of it, should they wish to do so.

**Comment by cbs228** [comment]
> Would you like to also provide changes to Makefile_mingw32?

v2 combines the two Makefiles with OS detection. I cannot test these changes as I do not have any Windows installations here. Can you test and push fixups as required?

> I prefer not to rename files that exist in g8bpq/ardop unless there is a good reason to do so.

👍

**Comment by pflarue** [comment]
Thanks for the additional commit.  

Yes, I'll test this new combined Makefile on both Windows and Linux.

**Comment by pflarue** [comment]
With only one minor change to correct the RM command for Windows, the new combined Makefile seems to work well.  

It is a better solution than my earlier addition of a second Makefile.

**Pull request merged**
